//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DOC_Status
    {
        public int status_id { get; set; }
        public string status_name { get; set; }
        public Nullable<int> status_value { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<bool> is_enabled { get; set; }
        public Nullable<int> status_group { get; set; }
    }
}
