//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DOC_Header
    {
        public DOC_Header()
        {
            this.DOC_Detail = new HashSet<DOC_Detail>();
        }
    
        public int header_id { get; set; }
        public string header_code { get; set; }
        public Nullable<System.DateTime> header_date { get; set; }
        public Nullable<System.DateTime> header_date_from { get; set; }
        public Nullable<System.DateTime> header_date_to { get; set; }
        public Nullable<int> header_supplier_id { get; set; }
        public string header_supplier_name { get; set; }
        public Nullable<int> header_customer_id { get; set; }
        public string header_customer_name { get; set; }
        public string header_address { get; set; }
        public string header_remark { get; set; }
        public Nullable<int> header_status { get; set; }
        public Nullable<bool> is_enabled { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
        public Nullable<int> subDocTypeID { get; set; }
        public Nullable<int> vat_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<int> header_warehouse_from { get; set; }
        public Nullable<int> header_warehouse_to { get; set; }
        public Nullable<decimal> header_total { get; set; }
        public Nullable<decimal> header_receive { get; set; }
        public Nullable<decimal> header_discout { get; set; }
        public Nullable<decimal> header_vat { get; set; }
        public Nullable<decimal> header_net { get; set; }
        public Nullable<decimal> header_deposit { get; set; }
        public Nullable<decimal> header_refund { get; set; }
        public Nullable<int> header_ref { get; set; }
        public Nullable<decimal> header_added { get; set; }
    
        public virtual ICollection<DOC_Detail> DOC_Detail { get; set; }
        public virtual DOC_SubDocType DOC_SubDocType { get; set; }
    }
}
