//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DOC_SubDocType
    {
        public DOC_SubDocType()
        {
            this.DOC_Header = new HashSet<DOC_Header>();
        }
    
        public int subDocTypeID { get; set; }
        public string subDocTypeCode { get; set; }
        public string subDocTypeName { get; set; }
        public int doctype_id { get; set; }
        public Nullable<int> seq { get; set; }
        public string description { get; set; }
        public Nullable<bool> isEnabled { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public string create_ip { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
        public string update_ip { get; set; }
    
        public virtual DOC_Doctype DOC_Doctype { get; set; }
        public virtual ICollection<DOC_Header> DOC_Header { get; set; }
    }
}
