//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DOC_Detail
    {
        public DOC_Detail()
        {
            this.DOC_Detail_Ingredient = new HashSet<DOC_Detail_Ingredient>();
        }
    
        public int detail_id { get; set; }
        public Nullable<int> header_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> product_price_id { get; set; }
        public string product_price_code { get; set; }
        public string product_price_name { get; set; }
        public Nullable<int> unit_id { get; set; }
        public string unit_name { get; set; }
        public Nullable<int> detail_qty { get; set; }
        public Nullable<decimal> detail_price { get; set; }
        public Nullable<decimal> detail_discount { get; set; }
        public Nullable<decimal> detail_total { get; set; }
        public Nullable<int> detail_status { get; set; }
        public string detail_remark { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<int> detail_warehouse { get; set; }
        public Nullable<int> used_qty { get; set; }
        public Nullable<int> unit_value { get; set; }
    
        public virtual DOC_Header DOC_Header { get; set; }
        public virtual MAS_Product MAS_Product { get; set; }
        public virtual MAS_Product_Price MAS_Product_Price { get; set; }
        public virtual ICollection<DOC_Detail_Ingredient> DOC_Detail_Ingredient { get; set; }
        public virtual MAS_Warehouse MAS_Warehouse { get; set; }
        public Nullable<int> subDocTypeID { get; set; }
    }
}
