//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class MAS_Unit
    {
        public MAS_Unit()
        {
            this.MAS_Product_Price = new HashSet<MAS_Product_Price>();
        }
    
        public int unit_id { get; set; }
        public string unit_code { get; set; }
        public string unit_name { get; set; }
        public Nullable<int> unit_value { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<bool> is_enabled { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
    
        public virtual ICollection<MAS_Product_Price> MAS_Product_Price { get; set; }
    }
}
