//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class MAS_Categories
    {
        public MAS_Categories()
        {
            this.MAS_Subcategories = new HashSet<MAS_Subcategories>();
        }
    
        public int categories_id { get; set; }
        public string categories_code { get; set; }
        public string categories_name { get; set; }
        public Nullable<double> categories_index { get; set; }
        public string description { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<bool> is_enabled { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
        public Nullable<int> categories_value { get; set; }
    
        public virtual ICollection<MAS_Subcategories> MAS_Subcategories { get; set; }
    }
}
