//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class MAS_SubDistrict
    {
        public int subDistrictID { get; set; }
        public string subDistrictCode { get; set; }
        public string subDistrictNameTH { get; set; }
        public string subDistrictNameEN { get; set; }
        public Nullable<int> districtID { get; set; }
        public Nullable<int> provinceID { get; set; }
        public Nullable<int> geographyID { get; set; }
        public Nullable<bool> isEnabled { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public string create_ip { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
        public string update_ip { get; set; }
    
        public virtual MAS_District MAS_District { get; set; }
    }
}
