//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class MAS_Province
    {
        public MAS_Province()
        {
            this.MAS_District = new HashSet<MAS_District>();
        }
    
        public int provinceID { get; set; }
        public string provinceCode { get; set; }
        public string provinceNameTH { get; set; }
        public string provinceNameEN { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> geographyID { get; set; }
        public Nullable<bool> isEnabled { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public string create_ip { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
        public string update_ip { get; set; }
    
        public virtual MAS_Country MAS_Country { get; set; }
        public virtual ICollection<MAS_District> MAS_District { get; set; }
        public virtual MAS_Geography MAS_Geography { get; set; }
    }
}
