//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class MAS_Supplier
    {
        public int supplier_id { get; set; }
        public string supplier_code { get; set; }
        public string supplier_name { get; set; }
        public string supplier_tel1 { get; set; }
        public string supplier_tel2 { get; set; }
        public string supplier_fax { get; set; }
        public string supplier_email { get; set; }
        public string supplier_address { get; set; }
        public Nullable<int> supplier_subdistict { get; set; }
        public Nullable<int> supplier_distict { get; set; }
        public Nullable<int> supplier_province { get; set; }
        public string supplier_zipcode { get; set; }
        public string description { get; set; }
        public Nullable<bool> is_enabled { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
    }
}
