//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class MSreplication_queue
    {
        public string publisher { get; set; }
        public string publisher_db { get; set; }
        public string publication { get; set; }
        public string tranid { get; set; }
        public byte[] data { get; set; }
        public Nullable<int> datalen { get; set; }
        public Nullable<int> commandtype { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public long orderkey { get; set; }
        public bool cmdstate { get; set; }
    }
}
