//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class MSsubscription_articles
    {
        public int agent_id { get; set; }
        public int artid { get; set; }
        public string article { get; set; }
        public string dest_table { get; set; }
        public string owner { get; set; }
        public string cft_table { get; set; }
    }
}
