//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class USR_Role_Submenu
    {
        public int role_id { get; set; }
        public int submenu_id { get; set; }
        public Nullable<bool> is_view { get; set; }
        public Nullable<bool> is_add { get; set; }
        public Nullable<bool> is_edit { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public Nullable<bool> is_search { get; set; }
    
        public virtual USR_Role USR_Role { get; set; }
        public virtual USR_Submenu USR_Submenu { get; set; }
    }
}
