//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class USR_Menu
    {
        public USR_Menu()
        {
            this.USR_Submenu = new HashSet<USR_Submenu>();
        }
    
        public int menu_id { get; set; }
        public string menu_code { get; set; }
        public string menu_name_eng { get; set; }
        public string menu_name_thai { get; set; }
        public string menu_url { get; set; }
        public Nullable<int> menu_index { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<bool> is_enabled { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
    
        public virtual ICollection<USR_Submenu> USR_Submenu { get; set; }
    }
}
