//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class USR_User_Profile
    {
        public int user_profile_id { get; set; }
        public Nullable<int> title_id { get; set; }
        public string emp_code { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> bithdate { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<int> subdistict { get; set; }
        public Nullable<int> distict { get; set; }
        public Nullable<int> province { get; set; }
        public string zipcode { get; set; }
        public Nullable<bool> is_enabled { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
        public string description { get; set; }
        public string card { get; set; }
        public byte[] pic { get; set; }
        public string pic_filename { get; set; }
    
        public virtual USR_Title USR_Title { get; set; }
    }
}
