//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class USR_Submenu
    {
        public USR_Submenu()
        {
            this.USR_Role_Submenu = new HashSet<USR_Role_Submenu>();
        }
    
        public int submenu_id { get; set; }
        public string submenu_code { get; set; }
        public string submenu_name_eng { get; set; }
        public string submenu_name_thai { get; set; }
        public string submenu_url { get; set; }
        public Nullable<int> submenu_index { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<bool> is_enabled { get; set; }
        public Nullable<int> menu_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
    
        public virtual USR_Menu USR_Menu { get; set; }
        public virtual ICollection<USR_Role_Submenu> USR_Role_Submenu { get; set; }
    }
}
