//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsStore.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class v_transAll
    {
        public int header_id { get; set; }
        public Nullable<int> header_customer_id { get; set; }
        public string header_customer_name { get; set; }
        public Nullable<int> header_supplier_id { get; set; }
        public string header_supplier_name { get; set; }
        public string header_address { get; set; }
        public Nullable<System.DateTime> header_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public decimal header_total { get; set; }
        public decimal header_discout { get; set; }
        public decimal header_vat { get; set; }
        public decimal header_net { get; set; }
        public decimal header_receive { get; set; }
        public decimal header_deposit { get; set; }
        public decimal header_refund { get; set; }
        public string header_remark { get; set; }
        public string doctype_name { get; set; }
        public Nullable<decimal> detail_discount { get; set; }
        public Nullable<decimal> detail_price { get; set; }
        public Nullable<int> detail_qty { get; set; }
        public Nullable<decimal> detail_total { get; set; }
        public string unit_name { get; set; }
        public string product_price_name { get; set; }
        public Nullable<System.DateTime> header_date_from { get; set; }
        public Nullable<System.DateTime> header_date_to { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string product_price_code { get; set; }
        public Nullable<int> used_qty { get; set; }
        public string PaymentNameTH { get; set; }
        public int doctype_id { get; set; }
        public string header_code { get; set; }
        public int detail_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string subDocTypeName { get; set; }
        public Nullable<int> subDocTypeID { get; set; }
        public string warehouse_name { get; set; }
        public Nullable<int> detail_warehouse { get; set; }
        public Nullable<int> payment_id { get; set; }
    }
}
